<template>
    <div class="rule__list-container">
        <div class="rule__list-title">Mining rules</div>
        <div class="rule__list-content">
            <ul class="rule__list-content-rules">
                <li>
                    <h3 class="question">1. How to Participate</h3>
                    <p><strong>.</strong> Select an active pool and stake corresponding token to participate in mining.</p>
                    <p><strong>.</strong> Users may unstake their tokens and claim the SUN earned anytime.</p>
                    <p><strong>.</strong> Users participated in previous pools may migrate their assets to new pools for more SUN rewards .(the SUN earned from previous pools will be transferred to the user's wallet).</p>
                    <p><strong>.</strong> Do not transfer TRX/TRC10/20 tokens to the contract, or your funds cannot be recovered. Participation is only available through the web page.</p>
                </li>
                <li>
                    <h3 class="question">2. Mining Pool Plan</h3>
                    <img src="src/assets/miningRules.png" alt="" class="rule_img" />
                </li>
                <li>
                    <h3 class="question">3. SUN Output and Distribution</h3>
                    <p>Currently all pools of SUN platform are mined at an even speed. Throughout the mining, a block will be generated in each pool every three seconds, each containing an identical amount of SUN rewards.</p>
                    <p>The SUN rewards generated by each block will be distributed to users based on the user's staking amount within the block in proportion to the total staking amount by all users within the block.</p>
                    <p>To sum up, the more and the longer users stake, the more SUN rewards they are eligible for.</p>
                </li>
                <li>
                    <h3 class="question">4. Formulas</h3>
                    <p><strong>Total amount of SUN a user can get</strong>=∑ (The user's percentage of Token within a block x Amount of SUN assigned by the pool within a block)</p>
                    <p><strong>.</strong> User's percentage of Token within a block = Amount of Token the user staked within a block / Total amount of Token staked within a block</p>
                    <p><strong>.</strong> Amount of SUN allocated to the pool within a block = Total amount of SUN allocated to the pool / Total number of blocks generated within 14 days</p>
                    <p><strong>.</strong> Amount of claimable SUN for the user = Total amount of SUN the user earned - Amount of SUN the user has claimed</p><br>

                    <p><strong>APY (annual percentage yield) </strong>= (Amount of SUN the pool produces per second x SUN price x 31536000) / Current amount of tokens staked</p>
                    <p><strong>.</strong> Current amount of Tokens staked: total staking amount in the Token pool (in TRX)</p>
                    <p><strong>.</strong> SUN price: real-time SUN/TRX quote</p>
                </li>
            </ul>
        </div>
    </div>
</template>

<script>
export default {
    data: function() {
        return {
            isActive: true,
        }
    },
    methods: {

    },
}
</script>

<style lang="scss">
    strong {
        font-weight: bolder;
    }

    .rule__list-container {
        width: 56.25%;
        margin: 0 auto;
        position: relative;
        z-index: 1;
    }

    .rule_img {
        width: 100%;
        max-width: 600px;
        margin: 0 auto;
        display: block;
    }

    .rule__list-title {
        font-family: HelveticaNeue-Medium;
        font-size: 46px;
        color: #fff;
        letter-spacing: 0;
        text-align: center;
        margin: 130px 0 110px 0;
    }

    .rule__list-content {
        background: #fff;
        box-shadow: 0 20px 40px 0 hsla(0,0%,58%,.06);
        border-radius: 15px;
        padding: 10px 0;
    }

    .question {
        font-family: PingFangSC-Regular;
        font-size: 18px;
        color: #1a1a1a;
        letter-spacing: .3px;
        margin-bottom: 6px;
    }

    .rule__list-content-rules {
        text-align: left;
        list-style-type: none;
        padding: 0;
        margin: 0;
    }

    .rule__list-content-rules li p {
        font-size: 13px;
        letter-spacing: 0;
        font-family: PingFangSC-Regular;
        color: #666;
        line-height: 22px;
        margin-bottom: 0;
    }

    .rule__list-content-rules li {
        padding: 20px 0;
        margin: 0 30px;
        border-bottom: 1px solid #efefef;
    }
</style>